"""Add enterprise auth fields

Revision ID: 0223c38351ab
Revises: 136d88a8fcb3
Create Date: 2026-07-19 05:15:51.715594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0223c38351ab'
down_revision: Union[str, None] = '136d88a8fcb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_device', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('otp_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('otp_expiry', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_expiry')
    op.drop_column('users', 'otp_hash')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'last_device')
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###
