"""Add visibility and community metrics

Revision ID: 124bddf94bff
Revises: f36d4e65f077
Create Date: 2026-07-12 08:00:40.409731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '124bddf94bff'
down_revision: Union[str, None] = 'f36d4e65f077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('visibility', sa.String(), nullable=False, server_default='PRIVATE'))
    op.add_column('reports', sa.Column('likes_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('reports', sa.Column('comments_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('reports', sa.Column('bookmarks_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('reports', sa.Column('views_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('reports', sa.Column('verification_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('reports', sa.Column('trending_score', sa.Float(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_reports_visibility'), 'reports', ['visibility'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_visibility'), table_name='reports')
    op.drop_column('reports', 'trending_score')
    op.drop_column('reports', 'verification_count')
    op.drop_column('reports', 'views_count')
    op.drop_column('reports', 'bookmarks_count')
    op.drop_column('reports', 'comments_count')
    op.drop_column('reports', 'likes_count')
    op.drop_column('reports', 'visibility')
    # ### end Alembic commands ###
