"""Add new columns to reports table

Revision ID: 136d88a8fcb3
Revises: 5dd7155796ae
Create Date: 2026-07-16 09:28:37.785134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '136d88a8fcb3'
down_revision: Union[str, None] = '5dd7155796ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('detected_type', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('pipeline_used', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('processing_time', sa.Float(), nullable=True))
    op.create_index(op.f('ix_reports_detected_type'), 'reports', ['detected_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_detected_type'), table_name='reports')
    op.drop_column('reports', 'processing_time')
    op.drop_column('reports', 'pipeline_used')
    op.drop_column('reports', 'detected_type')
    # ### end Alembic commands ###
