"""add classification routing fields

Revision ID: 5dd7155796ae
Revises: d5abeb622752
Create Date: 2026-07-13 02:27:56.916585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dd7155796ae'
down_revision: Union[str, None] = 'd5abeb622752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('user_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('reports', sa.Column('evidence_type', sa.String(), nullable=False))
    op.add_column('reports', sa.Column('classification_confidence', sa.Float(), nullable=True))
    op.add_column('reports', sa.Column('selected_pipeline', sa.String(), nullable=True))
    op.create_index(op.f('ix_reports_evidence_type'), 'reports', ['evidence_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_evidence_type'), table_name='reports')
    op.drop_column('reports', 'selected_pipeline')
    op.drop_column('reports', 'classification_confidence')
    op.drop_column('reports', 'evidence_type')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'user_id')
    # ### end Alembic commands ###
