"""Add generic cyber crime reports

Revision ID: f36d4e65f077
Revises: 2f4a5b6c7d8e
Create Date: 2026-07-12 07:57:51.830577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f36d4e65f077'
down_revision: Union[str, None] = '2f4a5b6c7d8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('category', sa.String(), nullable=False, server_default='Counterfeit Currency'))
    op.add_column('reports', sa.Column('title', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('description', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('incident_date', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('incident_time', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('location', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('priority', sa.String(), nullable=True))
    op.add_column('reports', sa.Column('evidence', sa.JSON(), nullable=True))
    op.alter_column('reports', 'denomination',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reports', 'image_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    op.alter_column('reports', 'status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='reportstatus'),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_reports_category'), 'reports', ['category'], unique=False)
    op.create_index(op.f('ix_reports_priority'), 'reports', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_priority'), table_name='reports')
    op.drop_index(op.f('ix_reports_category'), table_name='reports')
    op.alter_column('reports', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='reportstatus'),
               existing_nullable=False)
    op.alter_column('reports', 'image_url',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    op.alter_column('reports', 'denomination',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('reports', 'evidence')
    op.drop_column('reports', 'priority')
    op.drop_column('reports', 'location')
    op.drop_column('reports', 'incident_time')
    op.drop_column('reports', 'incident_date')
    op.drop_column('reports', 'description')
    op.drop_column('reports', 'title')
    op.drop_column('reports', 'category')
    # ### end Alembic commands ###
